---
abstract: 'Aligning (and pseudo aligning) biological sequences'
author:
  - 'Christos Argyropoulos <chrisarg@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.030, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Bio-SeqAlignment
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  Bio::SeqAlignment:
    file: lib/Bio/SeqAlignment.pm
    version: '0.02'
requires:
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/chrisarg/bio-seqalignment
  repository: https://github.com/chrisarg/bio-seqalignment.git
version: '0.02'
x_generated_by_perl: v5.38.0
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
